---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.ferron.sh
  resources:
  - ferroningresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.ferron.sh
  resources:
  - ferroningresses/finalizers
  verbs:
  - update
- apiGroups:
  - networking.ferron.sh
  resources:
  - ferroningresses/status
  verbs:
  - get
  - patch
  - update
