---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - deployments
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
- apiGroups:
  - networking.ferron.sh
  resources:
  - ferroncertificates
  - ferronproxies
  - ferronproxyselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.ferron.sh
  resources:
  - ferroncertificates/status
  - ferronproxies/status
  - ferronproxyselectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.ferron.sh
  resources:
  - ferronproxies/finalizers
  verbs:
  - update
