apiVersion: networking.ferron.sh/v1alpha1
kind: FerronProxy
metadata:
  labels:
    app.kubernetes.io/name: ferron-operator
    app.kubernetes.io/managed-by: kustomize
  name: ferronproxy-sample
spec:
  proxySelector: ferron
  config:
    routes:
      - host: localhost
        handle:
          - location: /
            proxy:
              service:
                name: ferron
                port:
                  number: 80
                scheme: http
                endpoint: /
