apiVersion: networking.ferron.sh/v1alpha1
kind: FerronIngress
metadata:
  labels:
    app.kubernetes.io/name: ferron-operator
    app.kubernetes.io/managed-by: kustomize
  name: ferroningress-sample
spec:
  config:
    routes:
      - host: localhost
        locations:
          - location: /
            proxy:
              service:
                name: ferron
                port: "80"
