//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronCertificate) DeepCopyInto(out *FerronCertificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronCertificate.
func (in *FerronCertificate) DeepCopy() *FerronCertificate {
	if in == nil {
		return nil
	}
	out := new(FerronCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FerronCertificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronCertificateList) DeepCopyInto(out *FerronCertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FerronCertificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronCertificateList.
func (in *FerronCertificateList) DeepCopy() *FerronCertificateList {
	if in == nil {
		return nil
	}
	out := new(FerronCertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FerronCertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronCertificateSpec) DeepCopyInto(out *FerronCertificateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronCertificateSpec.
func (in *FerronCertificateSpec) DeepCopy() *FerronCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(FerronCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronCertificateStatus) DeepCopyInto(out *FerronCertificateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronCertificateStatus.
func (in *FerronCertificateStatus) DeepCopy() *FerronCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(FerronCertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxy) DeepCopyInto(out *FerronProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxy.
func (in *FerronProxy) DeepCopy() *FerronProxy {
	if in == nil {
		return nil
	}
	out := new(FerronProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FerronProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxyConfig) DeepCopyInto(out *FerronProxyConfig) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]FerronProxyConfigRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxyConfig.
func (in *FerronProxyConfig) DeepCopy() *FerronProxyConfig {
	if in == nil {
		return nil
	}
	out := new(FerronProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxyConfigRoute) DeepCopyInto(out *FerronProxyConfigRoute) {
	*out = *in
	if in.Handle != nil {
		in, out := &in.Handle, &out.Handle
		*out = make([]FerronProxyRouteHandle, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxyConfigRoute.
func (in *FerronProxyConfigRoute) DeepCopy() *FerronProxyConfigRoute {
	if in == nil {
		return nil
	}
	out := new(FerronProxyConfigRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxyHandleProxy) DeepCopyInto(out *FerronProxyHandleProxy) {
	*out = *in
	out.Service = in.Service
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxyHandleProxy.
func (in *FerronProxyHandleProxy) DeepCopy() *FerronProxyHandleProxy {
	if in == nil {
		return nil
	}
	out := new(FerronProxyHandleProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxyList) DeepCopyInto(out *FerronProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FerronProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxyList.
func (in *FerronProxyList) DeepCopy() *FerronProxyList {
	if in == nil {
		return nil
	}
	out := new(FerronProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FerronProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxyProxyService) DeepCopyInto(out *FerronProxyProxyService) {
	*out = *in
	out.Port = in.Port
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxyProxyService.
func (in *FerronProxyProxyService) DeepCopy() *FerronProxyProxyService {
	if in == nil {
		return nil
	}
	out := new(FerronProxyProxyService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxyRouteHandle) DeepCopyInto(out *FerronProxyRouteHandle) {
	*out = *in
	out.Proxy = in.Proxy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxyRouteHandle.
func (in *FerronProxyRouteHandle) DeepCopy() *FerronProxyRouteHandle {
	if in == nil {
		return nil
	}
	out := new(FerronProxyRouteHandle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxySelector) DeepCopyInto(out *FerronProxySelector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxySelector.
func (in *FerronProxySelector) DeepCopy() *FerronProxySelector {
	if in == nil {
		return nil
	}
	out := new(FerronProxySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FerronProxySelector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxySelectorList) DeepCopyInto(out *FerronProxySelectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FerronProxySelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxySelectorList.
func (in *FerronProxySelectorList) DeepCopy() *FerronProxySelectorList {
	if in == nil {
		return nil
	}
	out := new(FerronProxySelectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FerronProxySelectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxySelectorSpec) DeepCopyInto(out *FerronProxySelectorSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxySelectorSpec.
func (in *FerronProxySelectorSpec) DeepCopy() *FerronProxySelectorSpec {
	if in == nil {
		return nil
	}
	out := new(FerronProxySelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxySelectorStatus) DeepCopyInto(out *FerronProxySelectorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxySelectorStatus.
func (in *FerronProxySelectorStatus) DeepCopy() *FerronProxySelectorStatus {
	if in == nil {
		return nil
	}
	out := new(FerronProxySelectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxyServicePort) DeepCopyInto(out *FerronProxyServicePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxyServicePort.
func (in *FerronProxyServicePort) DeepCopy() *FerronProxyServicePort {
	if in == nil {
		return nil
	}
	out := new(FerronProxyServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxySpec) DeepCopyInto(out *FerronProxySpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(FerronProxyTLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxySpec.
func (in *FerronProxySpec) DeepCopy() *FerronProxySpec {
	if in == nil {
		return nil
	}
	out := new(FerronProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxyStatus) DeepCopyInto(out *FerronProxyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxyStatus.
func (in *FerronProxyStatus) DeepCopy() *FerronProxyStatus {
	if in == nil {
		return nil
	}
	out := new(FerronProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronProxyTLS) DeepCopyInto(out *FerronProxyTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronProxyTLS.
func (in *FerronProxyTLS) DeepCopy() *FerronProxyTLS {
	if in == nil {
		return nil
	}
	out := new(FerronProxyTLS)
	in.DeepCopyInto(out)
	return out
}
