//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngress) DeepCopyInto(out *FerronIngress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngress.
func (in *FerronIngress) DeepCopy() *FerronIngress {
	if in == nil {
		return nil
	}
	out := new(FerronIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FerronIngress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngressConfig) DeepCopyInto(out *FerronIngressConfig) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]FerronIngressConfigRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngressConfig.
func (in *FerronIngressConfig) DeepCopy() *FerronIngressConfig {
	if in == nil {
		return nil
	}
	out := new(FerronIngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngressConfigRoute) DeepCopyInto(out *FerronIngressConfigRoute) {
	*out = *in
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]FerronIngressRouteLocation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngressConfigRoute.
func (in *FerronIngressConfigRoute) DeepCopy() *FerronIngressConfigRoute {
	if in == nil {
		return nil
	}
	out := new(FerronIngressConfigRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngressList) DeepCopyInto(out *FerronIngressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FerronIngress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngressList.
func (in *FerronIngressList) DeepCopy() *FerronIngressList {
	if in == nil {
		return nil
	}
	out := new(FerronIngressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FerronIngressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngressLocationProxy) DeepCopyInto(out *FerronIngressLocationProxy) {
	*out = *in
	out.Service = in.Service
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngressLocationProxy.
func (in *FerronIngressLocationProxy) DeepCopy() *FerronIngressLocationProxy {
	if in == nil {
		return nil
	}
	out := new(FerronIngressLocationProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngressProxyService) DeepCopyInto(out *FerronIngressProxyService) {
	*out = *in
	out.Port = in.Port
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngressProxyService.
func (in *FerronIngressProxyService) DeepCopy() *FerronIngressProxyService {
	if in == nil {
		return nil
	}
	out := new(FerronIngressProxyService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngressRouteLocation) DeepCopyInto(out *FerronIngressRouteLocation) {
	*out = *in
	out.Proxy = in.Proxy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngressRouteLocation.
func (in *FerronIngressRouteLocation) DeepCopy() *FerronIngressRouteLocation {
	if in == nil {
		return nil
	}
	out := new(FerronIngressRouteLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngressServicePort) DeepCopyInto(out *FerronIngressServicePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngressServicePort.
func (in *FerronIngressServicePort) DeepCopy() *FerronIngressServicePort {
	if in == nil {
		return nil
	}
	out := new(FerronIngressServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngressSpec) DeepCopyInto(out *FerronIngressSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngressSpec.
func (in *FerronIngressSpec) DeepCopy() *FerronIngressSpec {
	if in == nil {
		return nil
	}
	out := new(FerronIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FerronIngressStatus) DeepCopyInto(out *FerronIngressStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FerronIngressStatus.
func (in *FerronIngressStatus) DeepCopy() *FerronIngressStatus {
	if in == nil {
		return nil
	}
	out := new(FerronIngressStatus)
	in.DeepCopyInto(out)
	return out
}
